### 什么是Pytorch
###### PyTorch是一个基于Python的科学计算包，主要定位两类人群：
+ Numpy 的替代品，可以利用GPU的性能进行计算
+ 深度学习研究平台拥有足够的灵活性和速度

### 开始学习
### Tensors（张量）
Tensors类似于NumPy的ndarrays，同时Tensors可以使用GPU进行计算

In [1]:
from __future__ import print_function
import torch

构建一个5*3矩阵，不初始化

In [2]:
x = torch.empty(5,3)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


构造一个矩阵全为0，而且数据类型是long.

In [3]:
torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


构造一个张量，直接使用数据：

In [5]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


创建一个tensor基于已经存在的tensor。

In [6]:
x = x.new_ones(5,3,dtype=torch.double)
# new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)
# override dtype!
print(x)
# result has the same size

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-0.4411,  1.4363, -0.9810],
        [ 0.6356,  0.1591, -0.9534],
        [-0.5226,  1.0963,  1.3908],
        [-0.3781, -0.4079,  2.4331],
        [-1.1246,  0.3545,  0.9555]])


获取它的维度信息

In [8]:
print(x.size())

torch.Size([5, 3])


### 操作
在接下来的例子中，我们将会看到加法操作。加法：方式1

In [11]:
y = torch.rand(5,3)
print(x+y)

tensor([[ 0.0238,  1.9810, -0.9326],
        [ 0.8832,  0.3432, -0.2265],
        [-0.5105,  1.7660,  2.2002],
        [-0.1851, -0.3075,  3.2504],
        [-0.8870,  0.4080,  1.4275]])


加法：方式2

In [12]:
print(torch.add(x,y))

tensor([[ 0.0238,  1.9810, -0.9326],
        [ 0.8832,  0.3432, -0.2265],
        [-0.5105,  1.7660,  2.2002],
        [-0.1851, -0.3075,  3.2504],
        [-0.8870,  0.4080,  1.4275]])


加法：提供一个输出tensor作为参数

In [13]:
result = torch.empty(5,3)
torch.add(x,y,out=result)
print(result)

tensor([[ 0.0238,  1.9810, -0.9326],
        [ 0.8832,  0.3432, -0.2265],
        [-0.5105,  1.7660,  2.2002],
        [-0.1851, -0.3075,  3.2504],
        [-0.8870,  0.4080,  1.4275]])


加法：in-place

In [14]:
# adds x to y
y.add_(x)
print(y)

tensor([[ 0.0238,  1.9810, -0.9326],
        [ 0.8832,  0.3432, -0.2265],
        [-0.5105,  1.7660,  2.2002],
        [-0.1851, -0.3075,  3.2504],
        [-0.8870,  0.4080,  1.4275]])


### 注意：任何使张量会发生变化的操作都有一个前缀'_'.例如：
```
x.copy_(y)
```
,
```
x.t_()
```
,将会改变
```
x
```
.
你可以使用标准的Numpy类似的索引操作

In [15]:
print(x[:,1])

tensor([ 1.4363,  0.1591,  1.0963, -0.4079,  0.3545])


In [ ]:
改变大小：如果你想改变一个tensor的da